version: "3"
services:
  nodeContainer:
    build: .
    ports:
      — "8080:8080"
    depends_on:
      — mongoDB
    links:
      - "mongoDB:passport-jwt"
  mongoDB:
    image: mongo
  ports:
    — "27017:27017"
